//
// Created by Jorge Luis Vasquez on 1/05/2020.
//

#ifndef POOII_TAREA_2_ENTREGA_01_05_JORGEVASQUEZUTEC_FUNCIONES_H
#define POOII_TAREA_2_ENTREGA_01_05_JORGEVASQUEZUTEC_FUNCIONES_H

#endif //POOII_TAREA_2_ENTREGA_01_05_JORGEVASQUEZUTEC_FUNCIONES_H
